BizLandWebApp/Models/Service.cs
using System.ComponentModel.DataAnnotations;

namespace BizLandWebApp.Models
{
    public class Service
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; } = null!;
        [Required]
        public string IconName { get; set; } = null!;
        [Required]
        public string Description { get; set; }=null!;
    }
}

BizLandWebApp/Areas/Admin/Controllers/ServiceController.cs
using BizLandWebApp.DataContext;
using BizLandWebApp.Models;
using BizLandWebApp.ViewModels.ServiceVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace BizLandWebApp.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class ServiceController : Controller
{
    private readonly BizLandDbContext _context;
    public ServiceController(BizLandDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        List<Service> services = _context.Services.ToList();
        return View(services);
    }
    public IActionResult Read(int id)
    {
        Service? services= _context.Services.FirstOrDefault(s => s.Id == id);
        if(services == null) return NotFound();
        return View(services);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public async Task< IActionResult> Create(CreateServiceVM service)
    {
        if (!ModelState.IsValid) return View(service);

        if(_context.Services.Any(c => c.Title.Trim().ToLower() == service.Title.Trim().ToLower()))
        {
            ModelState.AddModelError("Title", "Service Already exist");
            return View(service);
        }
        Service newService = new Service()
        {
            Title= service.Title,
            Description= service.Description,
            IconName =service.IconName
        };
        await  _context.Services.AddAsync(newService);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
        Service? services= _context.Services.FirstOrDefault(c => c.Id == id);
        if(services == null) return NotFound();

        _context.Services.Remove(services);
        _context.SaveChanges();

        return RedirectToAction(nameof(Index));
    }
    public IActionResult Update(int id)
    {
        Service? services= _context.Services.FirstOrDefault(s => s.Id == id);
        if(services == null) return NotFound();
        return View(services);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Update(int id,Service newService)
    {
        Service? services = _context.Services.FirstOrDefault(s => s.Id == id);
        if (services == null) return NotFound();

        if (_context.Services.Any(c => c.Title.Trim().ToLower() == newService.Title.Trim().ToLower()))
        {
            ModelState.AddModelError("Title", "Service Already exist");
            return View();
        }
        services.Title = newService.Title;
        services.Description = newService.Description;
        services.IconName= newService.IconName;
     
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }
}

BizLandWebApp/Areas/Admin/Views/Service/Create.cshtml
@model CreateServiceVM

<h1>Service Create</h1>
<form class="container p-5" method="post">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control">
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
     <div class="form-group">
        <label asp-for="IconName"></label>
        <input asp-for="IconName" class="form-control">
        <span class="text-danger" asp-validation-for="IconName"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

BizLandWebApp/Areas/Admin/Views/Service/Index.cshtml
@model List<Service>

@{
    int count = 0;
}
<div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Services</h1>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3 d-flex justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                            <div>
                                <a class="btn btn-success px-5" asp-controller="Service" asp-action="Create">Create</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>№</th>
                                            <th>Title</th>
                                            <th>Description</th>
                                             <th>Icon</th>
                                            <th>Settings</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                        @foreach (Service item in Model)
                        {
                            <tr>
                                <td>@(++count)</td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td>@item.IconName</td>
                                <td>
                                    <div class="d-flex justify-content-around">
                                            <a asp-action="Read" asp-controller="Service" asp-route-id="@item.Id" ><button class="btn btn-info">Detail</button></a>
                                        <form method="get" asp-action="Update" asp-route-id="@item.Id">
                                            <a ><button class=" btn btn-warning">Edit</button></a>
                                        </form>
                                        <form method="post" asp-action="Delete" asp-route-id="@item.Id">
                                            <a><button class="btn btn-danger">Delete</button></a>
                                        </form>
                                    </div>
                                </td>
                             </tr>
                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

BizLandWebApp/Areas/Admin/Views/Service/Read.cshtml
@model Service
<h1>@Model.Id</h1>
<h1>@Model.IconName</h1>
<h1>@Model.Title</h1>
<h1>@Model.Description</h1>

BizLandWebApp/Areas/Admin/Views/Service/Update.cshtml
@model Service

<h1>Category Update</h1>

<form class="container p-5" method="post">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" id="exampleInputPassword1">
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label asp-for="IconName"></label>
        <input asp-for="IconName" class="form-control">
        <span class="text-danger" asp-validation-for="IconName"></span>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>