BizLandWebApp/Models/Team.cs
namespace BizLandWebApp.Models
{
    public class Team
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string Job { get; set; } = null!;
        public string ImageName { get; set; } = null!;
    }
}

BizLandWebApp/Areas/Admin/Controllers/TeamController.cs
using BizLandWebApp.DataContext;
using BizLandWebApp.Models;
using BizLandWebApp.ViewModels.TeamVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace BizLandWebApp.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = "Admin")]
public class TeamController : Controller
{
    private readonly BizLandDbContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public TeamController(BizLandDbContext context,IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }

    public async Task< IActionResult> Index()
    {
        List<Team> teams = await _context.Teams.ToListAsync();
        return View(teams);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateTeamVM team)
    {
        if (!ModelState.IsValid) return View();
        
        string newFilename = Guid.NewGuid().ToString() + team.Image.FileName;
        string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", "team", newFilename);
        
        using(FileStream fileStream=new FileStream(path, FileMode.CreateNew))
        {
            await team.Image.CopyToAsync(fileStream);
        }

        Team newTeam = new Team()
        {
            Name= team.Name,
            Job= team.Job,
            ImageName= newFilename
        };

        _context.Teams.Add(newTeam);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Read(int id)
    {
        Team? team=await _context.Teams.FindAsync(id);
        if(team==null) return NotFound();
        return View(team);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        Team? team = await _context.Teams.FindAsync(id);
        if (team==null) return NotFound();

        if(team.ImageName != null)
        {
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", "team");
            if(System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }
        _context.Teams.Remove(team);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Update(int id)
    {
        Team? team = await _context.Teams.FindAsync(id);
        if(team==null) return NotFound();

        UpdateTeamVM TeamVM= new UpdateTeamVM()
        {
            Name= team.Name,
            Job= team.Job
        };
        return View(TeamVM);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(int id,UpdateTeamVM newTeam)
    {

        Team? team=await _context.Teams.AsNoTracking().Where(t=> t.Id ==id).FirstOrDefaultAsync();
        if(team==null) return NotFound();

        if(!ModelState.IsValid)   return View(newTeam);
     
        if (newTeam.Image != null)
        {
            string path = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", "team", team.ImageName);
            using (FileStream fileStream = new FileStream(path, FileMode.Create))
            {
                await newTeam.Image.CopyToAsync(fileStream);
            }
            newTeam.ImageName = team.ImageName;
        }
        else
        {
            newTeam.ImageName = team.ImageName;
        }
        Team newDbTeam = new Team()
        {
            Id = team.Id,
            Name= newTeam.Name,
            Job= newTeam.Job,
            ImageName= newTeam.ImageName
        };
        _context.Teams.Update(newDbTeam);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

BizLandWebApp/Areas/Admin/Views/Team/Create.cshtml
@model CreateTeamVM

<div>
    <h1>Team Create</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="Job"></label>
            <input asp-for="Job" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Job"></span>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

BizLandWebApp/Areas/Admin/Views/Team/Index.cshtml

@model List<Team>
@{
    int count = 0;
}
<div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Teams</h1>
                   
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3 d-flex justify-content-between">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
                            <div>
                                <a class="btn btn-success px-5" asp-controller="Team" asp-action="Create">Create</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>№</th>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Work</th>
                                            <th>Settings</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach(Team item in Model)
                                    {
                                         <tr>
                                            <td>@(++count)</td>
                                            <td><img style="width:200px" src="~/assets/img/team/@item.ImageName"/></td>
                                            <td>@item.Name</td>
                                            <td>@item.Job</td>
                                            <td>
                                                <div class="d-flex justify-content-around">
                                                        <a asp-action="Read" asp-controller="Team" asp-route-id="@item.Id" ><button class="btn btn-info">Detail</button></a>
                                                    <form method="get" asp-action="Update" asp-route-id="@item.Id">
                                                        <a ><button class=" btn btn-warning">Edit</button></a>
                                                    </form>
                                                    <form method="post" asp-action="Delete" asp-route-id="@item.Id">
                                                        <a><button class="btn btn-danger">Delete</button></a>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

BizLandWebApp/Areas/Admin/Views/Team/Read.cshtml
@model Team

<div>
    <h2>@Model.Id</h2>
    <h2>@Model.Name</h2>
    <h2>@Model.Job</h2>
    <h2>
        <img style="width:200px" src="~/assets/img/team/@Model.ImageName"/>
    </h2>
</div>

BizLandWebApp/Areas/Admin/Views/Team/Update.cshtml
@model UpdateTeamVM

<div>
    <h1>Team Create</h1>
    <form class="container p-5" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="Job"></label>
            <input asp-for="Job" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Job"></span>
        </div>
        <div class="form-group">
            <label asp-for="Image"></label>
            <input asp-for="Image" class="form-control" id="exampleInputPassword1">
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>